name: pod
description: A riverpod type alias package
version: 0.14.0
homepage: https://github.com/TimWhiting/pod

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  riverpod: ^0.14.0

dev_dependencies:
  lints: ^1.0.0-0
